version: "3"
services:
    # PHP service
    app:
        container_name: ${PROJECT_NAME}-php-app
        build:
            context: ./
            dockerfile: "docker/configs/php/Dockerfile"
        environment:
            XDEBUG_CONFIG: "remote_host={{YOUR_IP_ADDRESS}}"
            PHP_IDE_CONFIG: "serverName=docker"
        volumes:
            - ./:/var/www
        networks:
            - ${PROJECT_NAME}_app_network
    # MySQL database service
    db:
        image: mysql:8.0
        container_name: ${PROJECT_NAME}-mysql-db
        restart: always
        ports:
            - "13303:3306"
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
            - ./docker/data/logs/mysql:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        networks:
            - ${PROJECT_NAME}_app_network
    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}-php-nginx
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "128m"
        ports:
            - 7003:80
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - ${PROJECT_NAME}_app_network
networks:
    url_converter_app_network:
        driver: bridge
